parent=keycloak
styles=css/styles.css
kcFormGroupClass=sub-field
kcLabelWrapperClass=sub-label-wrap
kcLabelClass=sub-label
kcInputWrapperClass=sub-input-wrap
kcInputClass=sub-input
kcInputErrorMessageClass=sub-field-msg
kcInputHelperTextBeforeClass=sub-field-help
kcInputHelperTextAfterClass=sub-field-help
kcContentWrapperClass=sub-group-wrap
kcFormGroupHeader=sub-group-title
kcInputClassRadio=sub-choice
kcInputClassRadioInput=sub-choice-input
kcInputClassRadioLabel=sub-choice-label
kcInputClassCheckbox=sub-choice
kcInputClassCheckboxInput=sub-choice-input
kcInputClassCheckboxLabel=sub-choice-label
kcInputClassRadioCheckboxLabelDisabled=sub-choice-label-disabled
